export const ALL_THEMES = [
  'apple', 'sea', 'mountain', 'robot', 'pizza', 'unicorn', 'castle', 'beach',
  'dragon', 'rocket', 'banana', 'ghost', 'tiger', 'moon', 'coffee', 'dinosaur',
  'rainbow', 'pirate', 'cactus', 'butterfly', 'elephant', 'guitar', 'sunflower',
  'octopus', 'cookie', 'volcano', 'penguin', 'crown', 'mushroom', 'spaceship',
  'panda', 'ice cream', 'wizard', 'turtle', 'fireworks', 'lion', 'cherry',
  'submarine', 'owl', 'hot dog', 'phoenix', 'frog', 'candy', 'train', 'starfish',
  'robot', 'palm tree', 'donut', 'zebra', 'lightning', 'cupcake', 'shark',
  'balloon', 'koala', 'diamond', 'whale', 'popcorn', 'eagle', 'lollipop',
  'crab', 'sunset', 'hedgehog', 'jellyfish', 'hamburger', 'peacock', 'snowman',
  'flamingo', 'waffle', 'kangaroo', 'thunder', 'pancake', 'giraffe', 'coconut',
  'firefly', 'squirrel', 'pretzel', 'ostrich', 'marshmallow', 'raccoon',
  'pineapple', 'tornado', 'sloth', 'brownie', 'parrot', 'waterfall', 'badger',
  'chocolate', 'seahorse', 'avalanche', 'platypus', 'noodle', 'fox', 'comet',
  'armadillo', 'pudding', 'wolf', 'meteor', 'anteater', 'sundae', 'bear',
  'galaxy', 'iguana', 'muffin', 'rhino', 'nebula', 'quokka', 'pie', 'scorpion',
  'airplane', 'airport', 'anchor', 'ant', 'backpack', 'bagel', 'bamboo', 'barn',
  'baseball', 'basketball', 'bat', 'beetle', 'bell', 'bicycle', 'binoculars',
  'birthday cake', 'black hole', 'blender', 'blueberry', 'boat', 'bomb', 'book',
  'boots', 'bow', 'brain', 'bridge', 'broccoli', 'broom', 'bubble', 'bucket',
  'bulldozer', 'bus', 'button', 'cabin', 'camera', 'campfire', 'canoe',
  'car', 'carrot', 'cat', 'cave', 'cell phone', 'cheese', 'chicken', 'chimney',
  'clock', 'cloud', 'clown', 'coat', 'compass', 'computer', 'cookie jar',
  'cow', 'credit card', 'crystal', 'cup', 'curtain', 'dagger', 'desk',
  'door', 'dragonfly', 'drum', 'duck', 'ear', 'earth', 'egg', 'electric guitar',
  'engine', 'envelope', 'eraser', 'eye', 'face', 'fan', 'feather', 'fence',
  'finger', 'fish', 'flag', 'flashlight', 'flower', 'flute', 'football',
  'forest', 'fork', 'fountain', 'fries', 'gamepad', 'garden', 'gate', 'gear',
  'glasses', 'globe', 'glove', 'goat', 'gold', 'golf', 'grapes', 'grass',
  'grill', 'grocery bag', 'hammer', 'hand', 'hat', 'headphones', 'heart',
  'helicopter', 'helmet', 'hill', 'honey', 'horse', 'hospital', 'house',
  'iceberg', 'island', 'jacket', 'jeans', 'joystick', 'juice', 'key',
  'keyboard', 'kite', 'knife', 'ladder', 'lamp', 'laptop', 'leaf', 'lemon',
  'library', 'lifeboat', 'light bulb', 'magnet', 'mailbox', 'map', 'marker',
  'microphone', 'microscope', 'milk', 'mirror', 'monkey', 'motorcycle',
  'mouse', 'music note', 'nail', 'necklace', 'net', 'newspaper', 'notebook',
  'oil', 'onion', 'orange', 'paintbrush', 'palette', 'paper', 'parachute',
  'park', 'passport', 'peach', 'pear', 'pen', 'pencil', 'phone', 'photo frame',
  'piano', 'pickup truck', 'pig', 'pillow', 'pinwheel', 'pipe', 'planet',
  'plank', 'plate', 'playground', 'pliers', 'pocket', 'police car', 'pool',
  'postcard', 'pot', 'power outlet', 'printer', 'pumpkin', 'purse', 'rabbit',
  'radio', 'raincoat', 'refrigerator', 'remote', 'ring', 'road', 'roller skate',
  'rope', 'rose', 'rug', 'sailboat', 'salad', 'sandwich', 'satellite',
  'saxophone', 'scarf', 'school', 'scissors', 'screwdriver', 'scroll',
  'seaweed', 'seed', 'shampoo', 'shoe', 'shopping cart', 'shovel', 'sink',
  'skateboard', 'skull', 'sky', 'sled', 'smoke', 'snail', 'snake', 'snowflake',
  'soap', 'sock', 'spacesuit', 'spider', 'spoon', 'spring', 'square',
  'stairs', 'stapler', 'statue', 'stethoscope', 'stove', 'streetlight',
  'suitcase', 'sunglasses', 'surfboard', 'swan', 'switch', 'table', 'tape',
  'taxi', 'teapot', 'telescope', 'tent', 'thermometer', 'ticket', 'tie',
  'toaster', 'toilet', 'tomato', 'toolbox', 'tooth', 'toothbrush', 'tower',
  'tractor', 'traffic light', 'treehouse', 'trophy', 'truck', 'trumpet',
  'umbrella', 'vacuum', 'vase', 'violin', 'volleyball', 'wallet', 'watch',
  'watermelon', 'wave', 'wheel', 'windmill', 'window', 'wine glass',
  'wrench', 'xylophone', 'yacht', 'yogurt', 'zoo'
]