spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${SERVER_PORT}

client.origin=${CLIENT_ORIGIN}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER}
spring.security.oauth2.resourceserver.jwt.audience=${AUTH0_AUDIENCE}

socketio.port=${SOCKET_PORT}

app.admin.email=${ADMIN_EMAIL}

logging.level.com.drawroyale=DEBUG